version: "3.9"

services:
  nginx:
    depends_on:
      - 'php'
      - 'sql'
    image: 'nginx:stable-alpine'
    volumes:
      - '.:/var/www/html/'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    ports:
      - '8000:80'

  php:
    build:
      context: './dockerfiles'
      dockerfile: 'php.dockerfile'
    volumes:
      - '.:/var/www/html:delegated'

  sql:
    image: 'mysql:5.7'
    env_file:
      - './env/mysql.env'
    ports:
      - '3306:3306'
